[project]
name = "ena-wizard-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.2",
    "polars>=1.33.1",
    "streamlit>=1.49.1",
    "streamlit-option-menu>=0.4.0",
    "tqdm>=4.67.1",
]
